GET http://localhost:3001/api/diagnoses
###
GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
        "name": "Kun Aguero Luukkainen",
        "dateOfBirth": "1971-04-09",
        "ssn": "090471-8890",
        "gender": "male",
        "occupation": "evangelist"
}
###
GET http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667
###
POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Routine health check",
  "date": "2023-07-01",
  "specialist": "Dr. Smith",
  "diagnosisCodes": ["S62.5", "M24.2"],
  "type": "HealthCheck",
  "healthCheckRating": 1    
}

###
POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Annual health check by employer",
  "date": "2023-07-02",
  "specialist": "Dr. Doe",
  "diagnosisCodes": ["H54.7"],
  "type": "OccupationalHealthcare",
  "employerName": "Tech Corp",
  "sickLeave": {
    "startDate": "2023-06-15",
    "endDate": "2023-06-20"
  }
}